AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::LanguageExtensions
Parameters:
  S3BucketNames:
    Type: CommaDelimitedList
Resources:
  # TODO: Replace with custom macro that creates a bucket and output for each S3 bucket name
  'Fn::ForEach::S3Buckets':
    - S3BucketName
    - Ref: S3BucketNames
    - '${S3BucketName}S3Bucket':
        Type: AWS::S3::Bucket
        Properties:
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256
          LifecycleConfiguration:
            Rules:
              - Status: Enabled
                ExpirationInDays: 1
Outputs:
  'Fn::ForEach::S3BucketNameOutputs':
    - S3BucketName
    - Ref: S3BucketNames
    - '${S3BucketName}S3BucketName':
        Value:
          Ref:
            'Fn::Sub': '${S3BucketName}S3Bucket'