AWSTemplateFormatVersion: 2010-09-09
Parameters:
  S3BucketNames:
    Type: CommaDelimitedList
Resources:
  # TODO: Replace with custom macro that creates a bucket and output for each S3 bucket name
  MessagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 1
            NoncurrentVersionExpiration:
              NewerNoncurrentVersions: 1
              NoncurrentDays: 1
Outputs:
  MessagesBucketName:
    Value: !Ref MessagesBucket