AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  InputTransformerFunctionName:
    Type: String
  DoublerFunctionName:
    Type: String
  FirstBucketName:
    Type: String
  SecondBucketName:
    Type: String
  OutOfBandDeploymentSupport:
    Type: String
    Default: "false"
Resources:
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Fn::Transform:
      Name: MacroNamesPrefix-AWSTestHarness-OutOfBandDeploymentSupport
      Parameters:
        Enabled: !Ref OutOfBandDeploymentSupport
    Properties:
      DefinitionUri: statemachine.asl.yaml
      DefinitionSubstitutions:
        InputTransformerFunctionName: !Ref InputTransformerFunctionName
        DoublerFunctionName: !Ref DoublerFunctionName
        FirstBucketName: !Ref FirstBucketName
        SecondBucketName: !Ref SecondBucketName
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref InputTransformerFunctionName
        - LambdaInvokePolicy:
            FunctionName: !Ref DoublerFunctionName
        - S3ReadPolicy:
            BucketName: !Ref FirstBucketName
        - S3WritePolicy:
            BucketName: !Ref SecondBucketName
Outputs:
  StateMachineArn:
    Value: !Ref StateMachine