AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  InputTransformerFunctionName:
    Type: String
  DoublerFunctionName:
    Type: String
  FirstTableName:
    Type: String
  FirstBucketName:
    Type: String
  SecondBucketName:
    Type: String
  MultiplierStateMachineArn:
    Type: String
  DataProcessorTaskDefinitionArn:
    Type: String
  ECSClusterArn:
    Type: String
  VpcId:
    Type: String
  SubnetIds:
    Type: String
  SecurityGroupIds:
    Type: String
  OutOfBandDeploymentSupport:
    Type: String
    Default: "false"
Resources:
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Fn::Transform:
      Name: MacroNamesPrefix-AWSTestHarness-OutOfBandDeploymentSupport
      Parameters:
        Enabled: !Ref OutOfBandDeploymentSupport
    Properties:
      DefinitionUri: statemachine.asl.yaml
      DefinitionSubstitutions:
        InputTransformerFunctionName: !Ref InputTransformerFunctionName
        DoublerFunctionName: !Ref DoublerFunctionName
        FirstTableName: !Ref FirstTableName
        FirstBucketName: !Ref FirstBucketName
        SecondBucketName: !Ref SecondBucketName
        MultiplierStateMachineArn: !Ref MultiplierStateMachineArn
        DataProcessorTaskDefinitionArn: !Ref DataProcessorTaskDefinitionArn
        ECSClusterArn: !Ref ECSClusterArn
        VpcId: !Ref VpcId
        SubnetIds: !Ref SubnetIds
        SecurityGroupIds: !Ref SecurityGroupIds
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref InputTransformerFunctionName
        - LambdaInvokePolicy:
            FunctionName: !Ref DoublerFunctionName
        - S3ReadPolicy:
            BucketName: !Ref FirstBucketName
        - S3WritePolicy:
            BucketName: !Ref SecondBucketName
        - DynamoDBReadPolicy:
            TableName: !Ref FirstTableName
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource:
                - !Ref MultiplierStateMachineArn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - states:DescribeExecution
                - states:StopExecution
              Resource:
                - !Sub ${MultiplierStateMachineArn}:*
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - ecs:RunTask
              Resource: !Ref DataProcessorTaskDefinitionArn
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: "*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - events:PutTargets
                - events:PutRule
                - events:DescribeRule
              Resource:
                - !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule
                - !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForECSTaskRule
Outputs:
  StateMachineArn:
    Value: !Ref StateMachine