AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  FirstTableName:
    Type: String
  SecondTableName:
    Type: String
  FirstBucketName:
    Type: String
  SecondBucketName:
    Type: String
  FirstFunctionName:
    Type: String
  FirstStateMachineArn:
    Type: String
  FirstTaskDefinitionArn:
    Type: String
  ECSClusterArn:
    Type: String
  VpcId:
    Type: String
  SubnetIds:
    Type: String
  SecurityGroupIds:
    Type: String
  OutOfBandDeploymentSupport:
    Type: String
    Default: "false"
Resources:
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Fn::Transform:
      Name: MacroNamesPrefix-AWSTestHarness-OutOfBandDeploymentSupport
      Parameters:
        Enabled: !Ref OutOfBandDeploymentSupport
    Properties:
      DefinitionUri: statemachine.asl.yaml
      DefinitionSubstitutions:
        FirstTableName: !Ref FirstTableName
        SecondTableName: !Ref SecondTableName
        FirstBucketName: !Ref FirstBucketName
        SecondBucketName: !Ref SecondBucketName
        FirstFunctionName: !Ref FirstFunctionName
        FirstStateMachineArn: !Ref FirstStateMachineArn
        FirstTaskDefinitionArn: !Ref FirstTaskDefinitionArn
        ECSClusterArn: !Ref ECSClusterArn
        VpcId: !Ref VpcId
        SubnetIds: !Ref SubnetIds
        SecurityGroupIds: !Ref SecurityGroupIds
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref FirstBucketName
        - S3WritePolicy:
            BucketName: !Ref SecondBucketName
        - DynamoDBReadPolicy:
            TableName: !Ref FirstTableName
        - DynamoDBWritePolicy:
            TableName: !Ref SecondTableName
        - LambdaInvokePolicy:
            FunctionName: !Ref FirstFunctionName
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource:
                - !Ref FirstStateMachineArn
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - states:DescribeExecution
                - states:StopExecution
              Resource:
                - !Sub ${FirstStateMachineArn}:*
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - ecs:RunTask
              Resource:
                - !Ref FirstTaskDefinitionArn
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: "*"
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - events:PutTargets
                - events:PutRule
                - events:DescribeRule
              Resource:
                - !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule
                - !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForECSTaskRule
Outputs:
  StateMachineArn:
    Value: !Ref StateMachine