AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  MacroNamesPrefix:
    Type: String
    Description: Optional prefix for all macro names
    Default: ""
Resources:
  OutOfBandDeploymentSupportMacro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: !Sub "${MacroNamesPrefix}AWSTestHarness-OutOfBandDeploymentSupport"
      Description: Adds resource metadata to support out-of-band deployments
      FunctionName: !Ref OutofBandDeploymentSupportFunction
  OutofBandDeploymentSupportFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          __CODE_PLACEHOLDER__:src/out_of_band_deployment_support.py
      Handler: index.handler
      Role: !GetAtt LambdaFunctionExecutionRole.Arn
      Runtime: python3.12
      Timeout: 5
  SecondSubMacro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: !Sub "${MacroNamesPrefix}AWSTestHarness-SecondSub"
      Description: Converts !SecondSub and "@{ ... }" into Fn::Sub and "${ ... }", respectively
      FunctionName: !Ref SecondSubFunction
  SecondSubFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          __CODE_PLACEHOLDER__:src/second_sub.py
      Handler: index.handler
      Role: !GetAtt LambdaFunctionExecutionRole.Arn
      Runtime: python3.12
      Timeout: 5
  TestDoublesMacro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: !Sub "${MacroNamesPrefix}AWSTestHarness-TestDoubles"
      Description: Generates a mapping from each template parameter, with the assumption that the parameter is a JSON object provided as a string
      FunctionName: !Ref TestDoublesFunction
  TestDoublesFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          __CODE_PLACEHOLDER__:src/test_doubles.py
      Handler: index.handler
      Role: !GetAtt LambdaFunctionExecutionRole.Arn
      Runtime: python3.12
      Timeout: 5
  LambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
